# Generated by Django 6.0 on 2026-01-07 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_workout', 'First Workout'), ('workouts_10', '10 Workouts'), ('workouts_50', '50 Workouts'), ('workouts_100', '100 Workouts'), ('workouts_500', '500 Workouts'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('streak_100', '100-Day Streak'), ('first_pr', 'First PR'), ('prs_10', '10 PRs'), ('prs_50', '50 PRs'), ('volume_10k', '10,000 kg Lifted'), ('volume_100k', '100,000 kg Lifted'), ('volume_1m', '1,000,000 kg Lifted'), ('bench_100', 'Bench 100kg'), ('squat_140', 'Squat 140kg'), ('deadlift_180', 'Deadlift 180kg'), ('ohp_60', 'OHP 60kg'), ('early_bird', 'Early Bird (5 AM workout)'), ('night_owl', 'Night Owl (10 PM workout)'), ('weekend_warrior', 'Weekend Warrior'), ('first_measurement', 'First Measurement'), ('weight_logged_30', '30 Days Weight Logged')], max_length=50, unique=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-unlocked_at', 'achievement_type'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('left_arm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('right_arm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('left_thigh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('right_thigh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('left_calf', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('right_calf', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('shoulders', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
