# Generated by Django 6.0 on 2026-01-07 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_achievement_bodymeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodyweight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('first_workout', 'First Workout'), ('workouts_10', '10 Workouts'), ('workouts_50', '50 Workouts'), ('workouts_100', '100 Workouts'), ('workouts_500', '500 Workouts'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('streak_100', '100-Day Streak'), ('first_pr', 'First PR'), ('prs_10', '10 PRs'), ('prs_50', '50 PRs'), ('volume_10k', '10,000 kg Lifted'), ('volume_100k', '100,000 kg Lifted'), ('volume_1m', '1,000,000 kg Lifted'), ('bench_100', 'Bench 100kg'), ('squat_140', 'Squat 140kg'), ('deadlift_180', 'Deadlift 180kg'), ('ohp_60', 'OHP 60kg'), ('early_bird', 'Early Bird (5 AM workout)'), ('night_owl', 'Night Owl (10 PM workout)'), ('weekend_warrior', 'Weekend Warrior'), ('first_measurement', 'First Measurement'), ('weight_logged_30', '30 Days Weight Logged')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bodyweight',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement_type')},
        ),
        migrations.AlterUniqueTogether(
            name='bodyweight',
            unique_together={('user', 'date')},
        ),
    ]
