# Generated by Django 6.0 on 2026-01-09 08:46

from django.db import migrations


def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Create default user if not exists
    if not User.objects.filter(username='batsal').exists():
        User.objects.create_user(
            username='batsal',
            password='Batsal123',
            is_staff=False,
            is_superuser=False
        )
    
    # Create admin if not exists
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            password='admin123'
        )


def reverse_func(apps, schema_editor):
    pass  # Don't delete users on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercise_unique_together_achievement_user_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_func),
    ]
