# Generated by Django 6.0 on 2026-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
